### PR TITLE
Sdk tools to array

### PR DESCRIPTION
**Pull request by halkeye**
I split them up into two arrays. I just wanted to download `android-23` but didn't want to mess with all the defaults.

### CODE REVIEW

**Comment by nickpack** [comment]
Thanks for the PR, this makes perfect sense - will get it merged later.

**Comment by halkeye** [comment]
Hey @nickpack, just a friendly reminder nudge on these two PRs

**Comment by halkeye** [comment]
2 month reminder :)

**Comment by nickpack** [comment]
Apologies for the delay - I changed jobs and dont have direct internet access at work, so have been a little offline :)

**Pull request merged**
